own_sdl2=0 was being ignored
RetroPie/RetroPie-Setup pull request #3279
Opened 2021-01-01 03:11 UTC by nhand42

The inivar own_sdl2 in /opt/retropie/configs/all/retropie.cfg was ignored for value "0".

2021-01-01 11:40 UTC, hhromic requested changes
Given that previously we have:
```bash
local own_sdl2=1
```
The actual fix is to just replace:
```
[[ "$ini_value" == "1" ]] && own_sdl2=1
```
into:
```bash
[[ "$ini_value" == "0" ]] && own_sdl2=0
```

not add a new conditional.

2021-01-01 11:44 UTC, nhand42 commented
> Given that previously we have:
> 
> ```shell
> local own_sdl2=1
> ```
> 
> The actual fix is to just replace:
> 
> ```
> [[ "$ini_value" == "1" ]] && own_sdl2=1
> ```
> 
> into:
> 
> ```shell
> [[ "$ini_value" == "0" ]] && own_sdl2=0
> ```
> 
> not add a new conditional.

Unless x11 platform is set, in which case the test for 1 is still required.

2021-01-01 11:45 UTC, hhromic commented
Ah that's a good point indeed. I don't know what is the actual desired behaviour.
Let's wait for another dev to chime in then. Thanks for noticing this bug anyway!

2021-01-03 05:41 UTC, joolswills commented
I'll sort this. I may change the logic a bit, but I agree it's broken.

2021-01-07 05:02 UTC, closed without merging