Use Libretro's RetroArch joypad autoconfig presets to generate button labels
RetroPie/RetroPie-Setup pull request #3362
Opened 2021-06-20 14:46 UTC by dankcushions

Whilst using Libretro's RetroArch joypad autoconfigs has proven problematic, we can still leverage this database in some interesting ways. This PR allows meaningful labels across the Retroarch menus, rather than the retropad abstract.

Eg, for a DualShock 4:
![IMG_5905](https://user-images.githubusercontent.com/13054748/122678233-cc453f80-d1dd-11eb-8a8e-9b5909d496ec.jpg)

2021-06-20 22:30 UTC, joolswills commented on scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh
> +    local autoconfig_preset=$(grep -rwl "/opt/retropie/configs/all/retroarch/autoconfig-presets/$input_driver" -e "$DEVICE_NAME" | head -1)
Can use `$configdir` here?

2021-06-20 22:32 UTC, joolswills commented
Apologies for the review as I missed that it's a WIP. Looks good though

2021-06-20 22:37 UTC, dankcushions commented on scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh
> +    local autoconfig_preset=$(grep -rwl "/opt/retropie/configs/all/retroarch/autoconfig-presets/$input_driver" -e "$DEVICE_NAME" | head -1)
good spot, done!

2021-06-20 22:39 UTC, dankcushions commented
@joolswills no problem! if you're happy with it in principle then I am happy putting it for review 👍

2021-07-21 01:25 UTC, joolswills commented
Sorry for the delay on this. Will test

2021-07-21 02:54 UTC, joolswills requested changes
Thanks. Works well from my testing. I would however like to move the autoconfig file location. As we use it as a read only reference, it could be checked out to the build folder and the configs copied to a subfolder of the retroarch `$md_inst`

2021-08-22 09:23 UTC, dankcushions commented
@joolswills thanks! was this what you had in mind?

2021-08-22 11:54 UTC, joolswills commented
This branch has conflicts btw so best to fix them before I review. Thanks

2021-08-22 18:46 UTC, dankcushions commented
Done a rebase! I believe it's good to review now.

2021-08-24 03:24 UTC, joolswills commented
Thanks. Looks good but I wonder if while moving it we should just do this at the source stage and copy it in install so it's part of the prebuilt bins. As `$md_inst` is cleaned on update it might make more sense than doing a new checkout over each time, although this would mean the version would be matched to when the binaries were built. It depends how important it is to have the latest version. As it's just for labels this may be enough.

2021-08-25 07:56 UTC, dankcushions commented
they probably don't change that much, but I suppose the same argument could be made for assets, overlays, shaders, etc. maybe the whole lot should be moved?

2021-08-25 07:59 UTC, joolswills commented
We install minimal assets so that's a bit different. Since we already handle the other stuff differently it's not a good idea to change that. It's also outside of this PR.

2021-08-25 08:55 UTC, joolswills commented
It's a small repo so I guess it's not a big issue to check it out at the configure stage so leave it. I'll merge this when I'm next working on stuff. Thanks

2021-09-08 02:17 UTC, joolswills approved these changes

2021-09-08 02:17 UTC, merged

2021-09-08 02:17 UTC, joolswills commented
Thanks.